### ISSUE TITLE
fetch_folder dejó de funcionar en migración a BeautifulSoup

### ISSUE THREAD

**Issue by salmundani** [franciscod/campus-fetch#5]
Si la página de la materia contiene un folder, la descarga falla con el siguiente error:
```
Traceback (most recent call last):
  File "/home/dani/Documents/repos/campus-fetch/dl.py", line 475, in <module>
    dl.fetch_course(*args)
  File "/home/dani/Documents/repos/campus-fetch/dl.py", line 174, in fetch_course
    self.parse_course(res)
  File "/home/dani/Documents/repos/campus-fetch/dl.py", line 179, in parse_course
    self.recurse_in_tabs(res)
  File "/home/dani/Documents/repos/campus-fetch/dl.py", line 222, in recurse_in_tabs
    self.recurse_in_tabs(newres)
  File "/home/dani/Documents/repos/campus-fetch/dl.py", line 222, in recurse_in_tabs
    self.recurse_in_tabs(newres)
  File "/home/dani/Documents/repos/campus-fetch/dl.py", line 222, in recurse_in_tabs
    self.recurse_in_tabs(newres)
  [Previous line repeated 2 more times]
  File "/home/dani/Documents/repos/campus-fetch/dl.py", line 226, in recurse_in_tabs
    self.parse_section(res)
  File "/home/dani/Documents/repos/campus-fetch/dl.py", line 278, in parse_section
    self.fetch_folder(href, slugify(title))
  File "/home/dani/Documents/repos/campus-fetch/dl.py", line 310, in fetch_folder
    content = self.parse_content(res, title)
  File "/home/dani/Documents/repos/campus-fetch/dl.py", line 235, in parse_content
    for iframe in content.find_all('iframe'):
AttributeError: 'NoneType' object has no attribute 'find_all'
```

La descarga funciona correctamente con el commit previo a la migración de BeautifulSoup. Se puede reproducir con:
```
MATERIAS = [
  ("BD-2022-C2", 3282),
]
```

**Comment by franciscod** [comment]
Gracias! Lo miro.

Muy util el dato de la materia donde pasa y muchas gracias por haber ido a
commit previos a revisar!

**Comment by salmundani** [comment]
Gracias a vos, me salvo muchas veces las papas esto :)

**Comment by franciscod** [comment]
Ahi parece que el ejemplo que pasaste quedó andando, cualquier cosa chiflá si encontras otra cosa! (no lo corrí para la materia completa)
